function plot_tas_2D(ZData1, YData1, XData1)
%CREATEFIGURE(ZData1, YData1, XData1)
%  ZDATA1:  surface zdata
%  YDATA1:  surface ydata
%  XDATA1:  surface xdata

%  Auto-generated by MATLAB on 25-May-2022 13:35:42

% Create figure
figure1 = figure('Color',[1 1 1]);
colormap(jet);

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.10367424425074 0.196772481568907 0.635583813660037 0.728227518431093]);
hold(axes1,'on');

% Create surface
surface('Parent',axes1,'ZData',ZData1,'YData',YData1,'XData',XData1,...
    'EdgeColor','none',...
    'CData',ZData1);

% Create ylabel
ylabel('Wavelength (nm)','FontName','Arial');

% Create xlabel
xlabel('Log [time (s)]','FontName','Arial');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-1 3]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[420 840]);
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'CLim',[-0.01 0],'Colormap',...
    [0.692307692307692 0 0;0.811339894673228 0.236157299490633 0.00249071915738583;0.874901641568308 0.459468186134853 0.0391398724732058;0.843088023088023 0.658619158619159 0.134534354534355;0.703747363747364 0.816292596292596 0.296252636252636;0.504884004884005 0.885592185592186 0.495115995115995;0.303747363747364 0.821762681762682 0.696252636252636;0.138192918192918 0.667570207570208 0.828240648240648;0.0402252068918735 0.468237688237688 0.830837064170398;0.00255978589311922 0.241489251489251 0.718186134852802;0 0 0.538461538461539],...
    'FontName','Arial','FontSize',8,'XTick',[-1 0 1 2 3]);
% Create colorbar
colorbar(axes1);

